#!/usr/bin/env bash
# Run all dotfiles installers.

set -e

# Get the dirname
__dirname=$(dirname $0)

# Install OS specific code
while true; do
  read -p "What operating system are you on? [macOS, ubuntu] " os
  case $os in
    mac|macos|macOS) echo "bootstrapping macOS..."; sh $__dirname/macos/bootstrap; break;;
    ubuntu) echo "bootstrapping ubuntu..."; sh $__dirname/ubuntu/bootstrap; break;;
    * ) echo "please enter a valid operating system"
  esac
done
echo

./manage/install.sh

# Find the installers and run them iteratively
find $__dirname -name install.sh \
  | /usr/bin/grep -ve manage \
  | while read installer ; do sh -c "${installer}" ; done
